### ISSUE TITLE
I can't get it to work

### ISSUE THREAD

**Issue by gondc** [oklas/react-breadcrumbs-dynamic#15] opened 2018-01-30 14:55 UTC
Hi, I don't know what I'm doing wrong. I run the example locally and it works perfectly, but when i try to implement it in my project does not work :(, I am using all the default props. Any help?

It should be rendering **Home / Table / Create** but is rendering only the last item
![image](https://user-images.githubusercontent.com/7863961/35572825-42ac56f8-05b4-11e8-8f7b-a7010f5eb143.png)

- **App.js**

![image](https://user-images.githubusercontent.com/7863961/35572546-98ed5ba8-05b3-11e8-9719-0e649fec8887.png)

- **Body.js**

![image](https://user-images.githubusercontent.com/7863961/35572513-8319c654-05b3-11e8-80fb-3d744b979004.png)

- **ABMMain.js**

![image](https://user-images.githubusercontent.com/7863961/35572675-e2c21322-05b3-11e8-9043-f83b8368ffe8.png)

- **ABMCrear.js**

![image](https://user-images.githubusercontent.com/7863961/35572635-cbb7eaee-05b3-11e8-8ebc-0aa32c7b6a1a.png)

**Comment by oklas** [comment] 2018-01-30 15:17
Hi! Fist of all I need to notice that I need to reproduce the problem to try to find out a reason. So it need to have a ready project with (check this: #12). You can contact me if you can share project to me but not to share it public or remove pivate code and share. 

Your current screen shots does not demonstrate a problem. Anyway check the rendered tree is it actually conatin all three instances of `<BreadcrumbsItem>`. For example place a unique string before each `<BreadcrumbsItem>` for example like this:

``` js
TheTable!<BreadcrumbsItem to="/ABMMain">Table</BreadcrumbsItem>
TheCreate!<BreadcrumbsItem to="/ABMMain/ABMCreate">Create</BreadcrumbsItem>
```

Check that all unique strings `TheTable!` and `TheCreate!` is exists on the page which mean that correspondent `<BreadcrumbsItem>` is instantiated. If unique strings does not exists provide its instantioanion by rendering. If unique strings is exists but breadcrumbs still is not appears than i need worked code to reproduce.

**Comment by gondc** [comment] 2018-01-30 15:36
Only renders one `<BreadcrumbsItem>`, the one I am currently at.

**Comment by gondc** [comment] 2018-01-30 15:46
Do I have to install `react-through`?

**Comment by oklas** [comment] 2018-01-30 17:48
The package `react-through` is available if application is runing without errors. If you suspects some problems in modules you need to do `rm -rf node_modules` and `npm cache clean` and then reinstall all again.

You will have one breadcrumbs item if only one `<BreadcrumbsItem>` element is rendered. 

try to render such code in one div:

``` js
<div>
  TheTable!<BreadcrumbsItem to="/ABMMain">Table</BreadcrumbsItem>
  TheCreate!<BreadcrumbsItem to="/ABMMain/ABMCreate">Create</BreadcrumbsItem>
</div>
```

If only one item will be visible - then I need code to reproduce. If two item is appear - then you need to inspect your code for instantiation of `<BreadcrumbsItem>`. Breadcrumbs show so much items how much <BreadcrumbsItem> with different property `to` is instantiated.

**Comment by gondc** [comment] 2018-01-30 18:14
It renders two items using that code, but a thing I noticed is that none of them is a link :/
So, I can't click them

**Comment by oklas** [comment] 2018-01-30 18:29
Fine. As far as about link: the reason is because default breadcrumbs item is an `<a>` tag. And the `<a>` tag does not have property `to` - it have property `href` for link. So to do it worked you need one of the:

* use special class (for example `<Link>`) wich is support `to` prop for link
* add a prop mapper `renameProps` or `duplicateProps` to `<Breadcrumbs/>` itself, like this:

``` js
<Breadcrumbs renameProps={{to:"href"}} />
 ```

So prop `to` will have be ranamed finally to prop `href` and link `<a>` will be worked.

**Comment by oklas** [comment] 2018-02-01 07:04
I hope you solve your issues. Any feedback and stars is very significant to know that my creations is on demand. Also followers can receive notifications about new features.

Now I close the issue. Feel free to write or reopen or create new if any.

**Closed by oklas** 2018-02-01 07:04 UTC

**Comment by oklas** [comment] 2018-02-22 08:32
Automatically renaming added in #16.

It does not require to specify `renameProps` from 1.0.14. 

So if `item` is 'a' or not specified instead of:

```js
    <Breadcrumbs renameProps={{to:"href"}} />
```

write simple:

```js
    <Breadcrumbs />
```
